# Generated by Django 5.0 on 2023-12-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_blog_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
