# Generated by Django 5.0 on 2023-12-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_usefulldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsefullData',
        ),
    ]
