# Generated by Django 4.2 on 2023-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_usefulldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('colors', models.CharField(choices=[('Blue', 'Blue'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Pink', 'Pink')], max_length=255)),
            ],
        ),
    ]
