# Generated by Django 4.2 on 2023-12-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_visasdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisasData',
        ),
    ]
