# Generated by Django 5.0.1 on 2024-01-31 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_blog_dislikes_blog_likes_blog_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='un_saved',
            field=models.ManyToManyField(related_name='un_blog_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
