# Generated by Django 5.0.1 on 2024-01-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_blog_un_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
