# Generated by Django 5.0.1 on 2024-01-31 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_blog_dislikes_remove_blog_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='un_saved',
        ),
        migrations.AlterField(
            model_name='blog',
            name='saved',
            field=models.ManyToManyField(related_name='saved_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
