# Generated by Django 5.0.1 on 2024-01-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_blog_un_saved_alter_blog_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='saved',
        ),
    ]
