# Generated by Django 5.0.1 on 2024-02-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
