# Generated by Django 5.0.1 on 2024-02-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_blog_images_extrablog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrablog',
            old_name='image',
            new_name='images',
        ),
    ]
