# Generated by Django 5.0.1 on 2024-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_rename_image_extrablog_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraBlog',
        ),
    ]
