# Generated by Django 5.0.1 on 2024-02-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_extrablog_exlinkadress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrablog',
            name='exLinkAdress',
        ),
        migrations.RemoveField(
            model_name='extrablog',
            name='exLinkName',
        ),
    ]
