# Generated by Django 5.0.1 on 2024-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_extrablog_exlinkadress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrablog',
            name='link_address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrablog',
            name='link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
