# Generated by Django 5.0.1 on 2024-02-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
