# Generated by Django 5.0.1 on 2024-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_systemuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
