# Generated by Django 5.0.1 on 2024-02-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_systemusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemusers',
            name='user',
        ),
    ]
