# Generated by Django 5.0.1 on 2024-02-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_remove_systemusers_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUsers',
        ),
    ]
