# Generated by Django 5.0.1 on 2024-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_delete_systemusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_yourself',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'Select Age Range'), (1, '9 - 16'), (2, '17 - 22'), (3, '23 - 28'), (4, '29 - 35'), (5, '36 - 40'), (6, '41 - 55'), (7, '55 and above')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('UZ', 'Uzbekistan'), ('DE', 'Germany'), ('IN', 'India'), ('CN', 'China'), ('GB', 'United Kingdom')], max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
