# Generated by Django 5.0.1 on 2024-02-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_userprofile_about_yourself_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefulldata',
            name='images',
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usefulldata',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
