# Generated by Django 5.0.1 on 2024-02-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_remove_usefulldata_images_usefulldata_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUsefull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='backend/static/Home/Assets/Images/BlogImages')),
                ('description', models.TextField()),
                ('link_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_address', models.URLField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.usefulldata')),
            ],
        ),
    ]
