# Generated by Django 5.0.1 on 2024-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_alter_visasdata_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrablog',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='extrausefull',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
