# Generated by Django 5.0.1 on 2024-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_alter_extrablog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulldata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backend/static/Home/Assets/Images/BlogImages'),
        ),
    ]
