# Generated by Django 5.0.1 on 2024-02-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_remove_usefulldata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='extrablog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_blogs',
        ),
        migrations.RemoveField(
            model_name='message',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messageusefull',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='messageusefull',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='VisasData',
        ),
        migrations.DeleteModel(
            name='ExtraBlog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='ExtraUsefull',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageUsefull',
        ),
        migrations.DeleteModel(
            name='UsefullData',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
