# Generated by Django 5.0.1 on 2024-02-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
    ]
