# Generated by Django 5.0.1 on 2024-02-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_remove_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_f_body',
            field=models.TextField(blank=True),
        ),
    ]
