# Generated by Django 5.0.1 on 2024-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_blog_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefulldata',
            old_name='description',
            new_name='description_f_body',
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='photo',
            field=models.ImageField(default='backend/static/Home/Assets/Images/BlogImages/ger-imTh_jkyd7QU.jpg', upload_to='backend/static/Home/Assets/Images/BlogImages'),
        ),
    ]
