# Generated by Django 5.0.1 on 2024-02-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_messageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='backend/static/Home/Assets/Images/BlogImages/germanyDefaultImages.jpg', upload_to='backend/static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='usefulldata',
            name='photo',
            field=models.ImageField(default='backend/static/Home/Assets/Images/BlogImages/germanyDefaultImages.jpg', upload_to='backend/static/Home/Assets/Images/BlogImages'),
        ),
    ]
