# Generated by Django 5.0.1 on 2024-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_blog_photo_alter_usefulldata_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefulldata',
            options={'verbose_name': 'Usefull', 'verbose_name_plural': 'Usefull Datas'},
        ),
    ]
