# Generated by Django 5.0.2 on 2024-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_alter_usefulldata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
