# Generated by Django 5.0.2 on 2024-02-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_extrausefull_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrausefull',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='link_name_de',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='link_name_en',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='link_name_ru',
        ),
        migrations.RemoveField(
            model_name='extrausefull',
            name='link_name_uz',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='description_f_body_de',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='description_f_body_en',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='description_f_body_ru',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='description_f_body_uz',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='tags_de',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='tags_ru',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='tags_uz',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='usefulldata',
            name='title_uz',
        ),
    ]
