# Generated by Django 5.0.2 on 2024-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_remove_extrausefull_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrausefull',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='link_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='link_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='link_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extrausefull',
            name='link_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='description_f_body_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='tags_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usefulldata',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
