# Generated by Django 5.0.2 on 2024-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_remove_extrausefull_description_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(blank=True, null=True)),
                ('images', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
