# Generated by Django 5.0.2 on 2024-02-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_popularposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularposts',
            name='images',
            field=models.ImageField(upload_to='backend/static/Home/Assets/Images/BlogImages'),
        ),
    ]
