# Generated by Django 5.0.2 on 2024-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_alter_popularposts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='backend/static/Home/Assets/Images/BlogImages/germanyDefaultImages.jpg', upload_to='static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='extrablog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='extrausefull',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='popularposts',
            name='images',
            field=models.ImageField(upload_to='static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='usefulldata',
            name='photo',
            field=models.ImageField(default='backend/static/Home/Assets/Images/BlogImages/germanyDefaultImages.jpg', upload_to='static/Home/Assets/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='visasdata',
            name='images',
            field=models.ImageField(upload_to='static/Home/Assets/Images/BlogImages'),
        ),
    ]
